### PR TITLE
remove old tests, unify under new

### PR DESCRIPTION
**Pull request by flowchartsman**

### CODE REVIEW

**Comment by nodece** [comment]
@flowchartsman I take a look your PR, I think you cannot ignore the testcase of test arg.

**Comment by flowchartsman** [comment]
I don't understand "ignore the testcase of test arg", but the main purpose was to address the [feedback](https://github.com/streamnative/pulsarctl/pull/420#pullrequestreview-731362056) that one full-lifecycle test is better, without `get_retention_test.go` `set_retention_test.go`, `remove_retention_test.go`, etc... None of the other commands in `pkg/ctl/topic` appear to follow that file format. But if everyone else is happy, I'm okay! I just want this command for my own use, so I am selfishly trying to help :)

**Comment by nodece** [comment]
@flowchartsman Do you mean only keep `retention_test.go`?

**Comment by flowchartsman** [comment]
Correct. At least, that's how [topic-level dispatch rate was implemented](https://github.com/streamnative/pulsarctl/commit/c268092697aa6ea252931f451eafc4fdbf38486f)

**Comment by nodece** [comment]
@flowchartsman thanks for your point. I update my code and has been merged into pulsarctl.

**Pull request closed without merging**
